- api/reference.md
- docs-structure.md
- feature-requests.md
- what-is-directus.md
Hi! I did an initial sweep across the Introduction section for basic typos and wording. Most are self-explanatory but a couple of notes:
what-is-directus.md:
-  Combined systems - you'd doubled up with "perhaps" from the previous point so changed this to "maybe".
- Re-worded your Directus App explanation to make it clear you were referring to a _user_ interface (you'd just used "interface" as part of the API term definition, so wanted to make it doubly clear this was different)
> Fixed minor typos and small wording improvements

- api/contributor/install-dev.md
Update the name to be in line with the rest of the documentation and the actual name in the repository
> Update example config name

- api/reference.md
I could not find anyware a list of all the field attributes.
> Added all the updatable attributes of a field

- api/reference.md
Type number is not a valid field type according to https://docs.directus.io/api/admin/field-types.html
> Field type

- api/reference.md
As @WellingGuzman says in https://github.com/directus/api/issues/601#issuecomment-440773346
> Remember to add `fields` to `lang` param

- advanced/api/configuration.md
- extensions/storage-adapters.md
Additionally to the endpoint handling in php, here comes the documentation for it.
See https://github.com/directus/api/pull/663
> Describe AWS S3 Endpoint

- extensions/storage-adapters.md
This confused me for a couple of minutes- thought I'd contribute so nobody else gets confused, haha
> Fix typo for sdk

- extensions/layouts.md
Hey there,
I wannted to add a bit more info to the layout section of the docs.
Please look for spelling mistakes or what I should change when something is not perfect.
Hope you like it.
> Added more info to the layout section

- guides/thumbnailer.md
Added tip to the thumbnailer docs, that clarifies the use of the thumbnailer with nginx a bit.
Also included an example of how to configure nginx to work correctly with the thumbnailer.
> Added tip about nginx configuration with the thumbnailer

- api/reference.md
To close "Raw Like Search" #92
> add wildcard examples

- advanced/app/standalone.md
Fixed broken link on setting up dev env on https://docs.directus.io/advanced/app/standalone.html#manually
> Fixed broken link

- extensions/custom-endpoints.md
Added missing semicolon in codesnippet
> Added missing semicolon

- api/data.md
Added missing single quote in snippet
> Added missing single quote in snippet

- advanced/server-setup.md
Closes https://github.com/directus/docs/issues/23
> Complete nginx configuration than half baked

- guides/soft-delete.md
Added docs for Soft Delete to describe the basics concept through examples. I'm not a native speaker and not sure if all concepts are explained right. So would be cool to get it checked. Thx
> Added docs for Soft Delete - fixes #139

- guides/relationships.md
The variable there has to refer to `movie.name` not just `name`.
> Fix visible column in many-to-many example

- advanced/app/plugins.md
Reflects the changes made in https://github.com/directus/app/pull/1615
> Update lodash name

- api/reference.md
URL template fixed to add the field to be deleted
> Fix the DELETE call for delete field

- getting-started/setup-checklist.md
@benhaynes Added some notes about docker. On second thought, a separate doc for each approach to installation probably goes further than we need. IMO these notes on how these OS level tips also apply with containerization might be helpful to a novice looking at taking the container approach to side-step OS-level setup complexities. 
Let me know your thoughts
> Setup checklist

- advanced/api/configuration.md
- api/reference.md
- extensions/custom-endpoints.md
- getting-started/installation.md
- guides/i18n.md
- guides/thumbnailer.md
Hope these are all self-explanatory.
> Fixed some broken / invalid links

- extensions/custom-endpoints.md
> Issue Fix #84

- api/reference.md
Add an example for adding data with below relations.
- O2M
- M2O
- M2M
> Add documentation for create relational data

- extensions/hooks.md
I should also either rename $container to $app or alternatively change container app::getInstance call to app::getInstance()::getContainer, in case that works
> fix example code

- guides/auth.md
> fix link for sdk implementation

- api/reference.md
Fixed https://github.com/directus/docs/issues/215
> Add default value of rate limit object and define the location

- api/reference.md
Ref. of https://github.com/directus/api/pull/1387
> Introducing new error code for failed mail sending

- guides/fields.md
> adds example for regex validation #137

- api/reference.md
> filename splitted into filename_disk and filename_download

- .vuepress/theme/global-components/InstallLink.vue
- .vuepress/theme/index.js
- .vuepress/theme/styles/palette.styl
- package-lock.json
- package.json
Lets us easily add custom components etc to the default theme
> Use derived theme for Docs

- guides/js-sdk.md
Fix this issue on the [docs](https://docs.directus.io/guides/js-sdk.html#reference)
> Fix format issue

- advanced/api/configuration.md
Fix this issue on the [docs](https://docs.directus.io/advanced/api/configuration.html#private-public-projects)
> Fix format issue (on private/public projects docs)

- extensions/hooks.md
Fix https://github.com/directus/api/issues/1328
> Add action hook in docs

- advanced/ddev.md
- Added a step to set Apache as a webserver.
- Added missing npm install.
- Re-organized compose install after ddev start
- other small changes.
> Update ddev documenation to use Apache and add missing steps.

- api/errors.md
Ref of https://github.com/directus/api/pull/1772
> Added error code

- guides/cli.md
Changing relates to Directus cli install setups.
> Updated command line interface doc

- extensions/modules.md
Fixed broken link in extensions/modules.
> Fix sdk link in modules.md

- guides/relationships.md
Changed the suggested field types for the ones required in v8.8.0. As per [2921](https://github.com/directus/app/issues/2921), this would make the solution.
> Changed the field types suggested

- guides/js-sdk.md
More info : https://github.com/directus/directus/discussions/2823
> Add createUser() method

- api/activity.md
> added status-update action type

- advanced/api/data.md
This includes a single update example using Zend and Directus' TableGateway. 
It was surprisingly difficult for me to find any example which would work with a "tableGateway" and would update a table.
> Include Zend Update example

- guides/js-sdk.md
Add documentation for the getAsset() and getAssetUrl() methods of the following PR: <https://github.com/directus/sdk-js/pull/171>
> ✨ Document the getAsset() and getAssetUrl methods
