directus/docs

- api/reference.md
During the reading of documentation I spotted some typos.
> Fix typos in the documentation

- api/contributor-guide/core-database-overview.md
- what-is-directus.md
Hello!
I found some 'receives' misspelled in the documentation as 'recieves'.
> Fix 'receive' typos in documentation

- app/contributor-guide/install-dev.md
Hi! Found another typo while reading the docs.
Also added a period at the end of the warning to keep it consistent with the rest of the pages.
> Fix typo in setup environment

- api/admin/configure-with-app.md
I was confused as manual configuration is available, but this is app configuration haha.
> Unimportant; Wording update

- advanced/api/migrations.md
the current command fails with `The file "phinx.yml" does not exist`. 
the config path `-c config/migrations.php` has to be added to the end of the `create:seed` command as well.
> fix command for UserSeed Example

- guides/relationships.md
I have struggled for hours trying to set it up translations and I'd like be further develop the provided instructions with key details that made it work in my case, namely:
* The fact of not using M2O fields when defining the foreign keys, it turns out it is not necessary at all
* Set the _language foreign key_ field with type `lang`
> Updated translations instructions

- advanced/deploying-versions.md
The `*` is not needed when doing `cp -r folder/ toFolder/`. It throws errors instead.
> Fix bash commands

- graphql/configure.md
Remove the graphql branch references from documentation.
> Update GraphQL documentation.

- getting-started/installation.md
PHP extension `libapache2-mod-php` was missing in the docs, this should prevent the app from not finding the API
> Updated required php extensions

- extensions/interfaces.md
- extensions/layouts.md
I spent an hour or so trying to figure out why the server was giving me 500 errors when loading my extension. Finally realized I'm supposed to transpile the `.vue` files myself. Updated docs to reflect that information.
> Clarify that you need to transpile .vue files when making custom extensions

- extensions/hooks.md
On almost all the example scripts for hooks there was the "<?php" at the start missing. 
This caused me a lot of trouble because I copied a script from there without the <?php and my backend broke because of this. It wasn't reachable anymore.
As it is already present in the last example script and  for example also in custom endpoint examples of the docs, I think it should be fine to add it here, too.
> Add "<?php" on top of hooks example scripts

- extensions/hooks.md
API is not supporting the after for any filter hooks. So removed it from DOC.
Fixed https://github.com/directus/api/issues/1364
> Update Filter Hooks

- extensions/hooks.md
https://github.com/directus/api/issues/1328
The documentation seems not to be correct for action hooks. I've got action hooks working successfully when changing the parameters order.
But be aware: this is a suggestion: i've didn't tested this for web-hooks
> Seems to be wrong parameters order for hooks in documention

- extensions/hooks.md
Fixes https://github.com/directus/api/issues/1364 (as https://github.com/directus/docs/pull/218 does not)
The fix in pull-request 218 seems wrong to me as :after and :before has to be set explicitly for create- and update- filters.
> Fix for https://github.com/directus/api/issues/1364

- sdk/js.md
Storage adapter requires a `removeItem` method.
> Update documentation about storage used by JS SDK

- getting-started/contributing.md
replaced `master` with `develop` as the master branch is used for the latest tag and not the actual development
> Updated contributing guide (master -> develop)

- sdk/js.md
I just spent 30 minutes trying to figure out why I was getting a 403 back from the API. Turns out I wasn't `await`ing on `client.login()`. Additionally, since I'm building a custom extension, I didn't even need to login! This also clarifies how to authenticate when building an extension.
> Clarify how to log in and that login() is async

- getting-started/contributing.md
It was pointing at `directus/directus` instead of `directus/docs`
> Fix link to directus documentation repo

- advanced/api/configuration.md
With the new release the cmd param for the project name was changed to `k` can be seen https://github.com/directus/api/blob/2697381e5e6239153334ad052e680504204b64cb/src/core/Directus/Console/Modules/InstallModule.php#L69
> Update on the name of project

- api/projects.md
It felt like all required items are in the example apart from the token
> Update project create so the example includes required super_admin_token

- docker/environment.md
- extensions/storage-adapters.md
See https://github.com/directus/api/pull/1807
Note: the change in docker/environment.md is based on the guess on how the env names are generated. I couldn't find the code that confirms if this the correct casing
> Update S3 Storage options to match API changes

- api/authentication.md
The standard installation following this documentation does not support using the authentication header option for authenticating API calls, due to apache stripping the header from call. Since it is listed as the first option, many people will probably experience this error. I think an explanation here makes sense - since the configuration is only needed if you want to use the authorization header.
> Clarify setup needed for authentication header

- installation/docker.md
Hi,
This is the documentation update for the following PR https://github.com/directus/docker/pull/99/commits
Thanks
> Use docker networks

- api/fields.md
updated the 'Fields > Retrieve a field' endpoint at:
https://docs.directus.io/api/fields.html#retrieve-a-field
> Update fields.md to fix the api endpoint in Fields

- api/relations.md
I believe there's a mistake in the api reference documentation example. "Create a relation" https://docs.directus.io/api/relations.html#create-a-relation response has field_one set to null while I was expecting it to be "books" from what was passed on the request.
> fix documentation example

- api/users.md
In the documentation https://docs.directus.io/api/users.html#create-a-user, the fields 'first_name' and 'last_name' are required, but in the example they are not sent. I believe it doesn't make sense to keep the example that way.
> required fields in example.

- api/roles.md
I think the name attribute is not necessary to update a role because it's not in the example, also because it's an update. So I removed the 'required' description at name attribute.
https://docs.directus.io/api/roles.html#update-a-role
> Fix optional attribute at update role

- api/query/page.md
The page warning at the top is incorrect. 
The current one is `?limit=10&page=3meta=*` which won't give the desired result because an ampersand is missing. Kindly change to `?limit=10&page=3&meta=*`
> Update top page warning

- installation/docker.md
It is unclear where to navigate  after finishing the installation guide; add step to navigate to sign in page.
> (docs) update docker installation guide

- advanced/api/data.md
~In my previous PR I put the documentation to update a table in the wrong spot - This PR fixes that. It's now where it should belong.~
Also, on the same part, I fixed the code where a variable was silently overwritten. It was working, however, it's a bad practice and could lead to unexpected behaviour (Trying to access `$data` under those lines).
> Corrected the location of the update table part
